import io
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import h5py
import numpy as np
import rasterio

from adapters.base import build_dataset_id, write_meta


TIME_RE = re.compile(r"_(\d{10})_")
RESOLUTION_RE = re.compile(r"(?P<resolution>\d+(?:KM|km)|\d+P\d+|\d+\.\d+)")
DEFAULT_NC_VARIABLES = ("Tair_f_inst", "Rainf_tavg", "AvgSurfT_inst", "Wind_f_inst")
DEFAULT_GRIB_VARIABLES = ("TMP", "SPFH", "UGRD", "VGRD")
COMMON_NC_DISPLAY_VARIABLES = (
    "Tair_f_inst",
    "Rainf_tavg",
    "TotalPrecip_tavg",
    "Wind_f_inst",
    "Qair_f_inst",
    "Psurf_f_inst",
    "AvgSurfT_inst",
    "SoilMoist_inst",
    "SoilTemp_inst",
    "SWdown_f_tavg",
)


def process_file(file_path: str, data_type: str = "CMA") -> dict[str, Any]:
    return _process_files([Path(file_path).resolve()], data_type=data_type)


def process_files(file_paths: list[str], data_type: str = "CMA") -> dict[str, Any]:
    paths = [Path(path).resolve() for path in file_paths]
    if not paths:
        raise ValueError("CMA adapter requires at least one file.")
    return _process_files(paths, data_type=data_type)


def _process_files(paths: list[Path], data_type: str = "CMA") -> dict[str, Any]:
    paths = sorted(paths, key=lambda item: _parse_time_from_name(item) or item.name)
    source_file = paths[0]
    suffix = source_file.suffix.lower()
    if any(path.suffix.lower() != suffix for path in paths):
        raise ValueError("CMA multi-file parsing requires files with the same extension.")

    if suffix == ".nc":
        product = _inspect_nc_product(source_file, paths)
        file_format = "NC"
    elif suffix in {".grib", ".grib2"}:
        product = _inspect_grib_product(source_file, paths)
        file_format = "GRIB"
    else:
        raise ValueError(f"CMA adapter only supports .nc, .grib and .grib2 files: {source_file.name}")

    frontend_meta = _build_frontend_meta(source_file, product)
    weather_info = _build_weather_info(frontend_meta, product)
    meta_file = source_file.with_name(f"{source_file.name}.meta.json")
    source_files: str | list[str] = (
        [path.as_posix() for path in paths]
        if len(paths) > 1
        else source_file.as_posix()
    )

    meta = {
        "schema_version": "1.0",
        **frontend_meta,
        "dataset_id": build_dataset_id(source_file),
        "data_type": data_type,
        "file_format": file_format,
        "source_file": source_files,
        "meta_file": meta_file.as_posix(),
        "png_files": [],
        "default_png": None,
        "default_variable": product["primary_variable"],
        "variables": _schema_variables(product),
        "composites": [],
        "times": [_iso_time(value) for value in product["times"]],
        "frames": product["frames"],
        "levels": product["levels"],
        "bbox": product["extent"],
        "weather_info": weather_info,
        "file_detail": _file_detail(source_file, meta_file, file_format, len(paths)),
        "time_detail": _time_detail(product),
        "spatial": _spatial_detail(product),
        "extra": {
            "status": "parsed",
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "note": "CMA CRA40-Land metadata generated by cma_adapter.py.",
            "cma": {
                "product_type": product["product_type"],
                "product_name": product["product_name"],
                "primary_variable": product["primary_variable"],
                "primary_unit": _clean_unit(product["primary_unit"]),
            },
            "era5": {},
            "gfs": {},
            "himawari": {},
            "radar": {},
            "wrf": {},
        },
    }

    write_meta(meta_file, meta)
    return meta


def _inspect_nc_product(source_file: Path, files: list[Path] | None = None) -> dict[str, Any]:
    files = files or _series_files(source_file, "*.nc")
    sample = files[0]
    scope = _infer_scope(source_file)
    variables: list[dict[str, Any]] = []
    levels: set[str] = set()
    trend: list[float] = []

    with _open_hdf(sample) as dataset:
        lat = np.array(dataset["lat"][:], dtype="float64")
        lon = np.array(dataset["lon"][:], dtype="float64")
        lat_min, lat_max = float(np.nanmin(lat)), float(np.nanmax(lat))
        lon_min, lon_max = float(np.nanmin(lon)), float(np.nanmax(lon))
        grid_shape = [int(lat.size), int(lon.size)]

        for name in dataset.keys():
            item = dataset[name]
            if not isinstance(item, h5py.Dataset) or name in {"lat", "lon"}:
                continue
            attrs = {key: _decode_attr(value) for key, value in item.attrs.items()}
            dims = _nc_dims(item.shape, grid_shape)
            if len(item.shape) == 3:
                levels.add(_profile_level_name(item.shape[0]))
            variables.append(
                {
                    "name": name,
                    "long_name": str(attrs.get("long_name") or name),
                    "unit": str(attrs.get("units") or ""),
                    "shape": [int(size) for size in item.shape],
                    "dtype": str(item.dtype),
                    "dims": dims,
                    "missing": _first_number(attrs.get("_FillValue") or attrs.get("missing_value")),
                }
            )

    primary = _pick_variable([item["name"] for item in variables], DEFAULT_NC_VARIABLES)
    stat_names = [item["name"] for item in variables if item["name"] in COMMON_NC_DISPLAY_VARIABLES]
    if primary not in stat_names:
        stat_names.append(primary)
    variable_stats = {name: _nc_stats(files, name) for name in stat_names}
    stats = variable_stats.get(primary) or _nc_stats(files, primary)
    trend = _nc_trend(files, primary)

    times = [_parse_time_from_name(path) for path in files]
    times = [item for item in times if item]
    resolution = _resolution(lon_min, lon_max, grid_shape[1], lat_min, lat_max, grid_shape[0])

    return {
        "product_type": "LAND_NC",
        "product_name": "CMA-RA/Land 陆面分析数据（NC）",
        "region": scope["region"],
        "resolution_label": scope["resolution_label"],
        "coverage": scope["coverage"],
        "files": [path.name for path in files],
        "frames": _build_frames(files, [lon_min, lat_min, lon_max, lat_max]),
        "file_count": len(files),
        "times": times,
        "time_start": _format_time(times[0]) if times else "",
        "time_end": _format_time(times[-1]) if times else "",
        "time_resolution_hours": _time_resolution_hours(times),
        "extent": [lon_min, lat_min, lon_max, lat_max],
        "range": _format_range([lon_min, lat_min, lon_max, lat_max]),
        "grid_shape": grid_shape,
        "grid": f"{grid_shape[1]} x {grid_shape[0]}",
        "resolution": resolution,
        "levels": sorted(levels) or ["surface"],
        "variables": variables,
        "variable_names": [item["name"] for item in variables],
        "primary_variable": primary,
        "primary_unit": _variable_field(variables, primary, "unit"),
        "primary_long_name": _variable_field(variables, primary, "long_name"),
        "missing": _variable_field(variables, primary, "missing") or "-9999",
        "stats": stats,
        "variable_stats": variable_stats,
        "trend": trend,
    }


def _inspect_grib_product(source_file: Path, files: list[Path] | None = None) -> dict[str, Any]:
    files = files or _series_files(source_file, "*.grib*")
    sample = files[0]
    scope = _infer_scope(source_file)
    variables: list[dict[str, Any]] = []

    with rasterio.open(sample) as dataset:
        left, bottom, right, top = (float(value) for value in dataset.bounds)
        grid_shape = [int(dataset.height), int(dataset.width)]
        for band in range(1, dataset.count + 1):
            tags = dataset.tags(band)
            variables.append(
                {
                    "name": tags.get("GRIB_ELEMENT", f"band{band}"),
                    "long_name": tags.get("GRIB_COMMENT", tags.get("GRIB_ELEMENT", f"band{band}")),
                    "unit": tags.get("GRIB_UNIT", ""),
                    "level": dataset.descriptions[band - 1] or tags.get("GRIB_SHORT_NAME", ""),
                    "band": band,
                    "short_name": tags.get("GRIB_SHORT_NAME", ""),
                    "forecast_seconds": tags.get("GRIB_FORECAST_SECONDS", ""),
                }
            )

    primary = _pick_variable([item["name"] for item in variables], DEFAULT_GRIB_VARIABLES)
    variable_names = sorted({item["name"] for item in variables})
    variable_stats = {name: _grib_stats(files, name) for name in variable_names}
    stats = variable_stats.get(primary) or _grib_stats(files, primary)
    trend = _grib_trend(files, primary)
    times = [_parse_time_from_name(path) for path in files]
    times = [item for item in times if item]
    resolution = _resolution(left, right, grid_shape[1], bottom, top, grid_shape[0])

    return {
        "product_type": "FORCING_GRIB",
        "product_name": "CMA-RA/Land 大气驱动融合数据（GRIB）",
        "region": scope["region"],
        "resolution_label": scope["resolution_label"],
        "coverage": scope["coverage"],
        "files": [path.name for path in files],
        "frames": _build_frames(files, [left, bottom, right, top]),
        "file_count": len(files),
        "times": times,
        "time_start": _format_time(times[0]) if times else "",
        "time_end": _format_time(times[-1]) if times else "",
        "time_resolution_hours": _time_resolution_hours(times),
        "extent": [left, bottom, right, top],
        "range": _format_range([left, bottom, right, top]),
        "grid_shape": grid_shape,
        "grid": f"{grid_shape[1]} x {grid_shape[0]}",
        "resolution": resolution,
        "levels": sorted({item["level"] for item in variables if item["level"]}) or ["surface"],
        "variables": variables,
        "variable_names": variable_names,
        "primary_variable": primary,
        "primary_unit": _variable_field(variables, primary, "unit"),
        "primary_long_name": _variable_field(variables, primary, "long_name"),
        "missing": "NaN",
        "stats": stats,
        "variable_stats": variable_stats,
        "trend": trend,
    }


def _build_frontend_meta(source_file: Path, product: dict[str, Any]) -> dict[str, Any]:
    variable_label = product["primary_long_name"] or product["primary_variable"]
    time_label = _time_span(product)
    return {
        "file": source_file.name,
        "element": f"{product['primary_variable']} - {variable_label}",
        "time": time_label,
        "level": " / ".join(product["levels"][:3]),
        "range": product["range"],
        "grid": product["grid"],
        "missing": str(product["missing"]),
        "unit": _clean_unit(product["primary_unit"]),
        "vars": str(len(product["variable_names"])),
        "steps": str(len(product["times"]) or product["file_count"]),
        "extent": product["extent"],
    }


def _build_weather_info(frontend_meta: dict[str, Any], product: dict[str, Any]) -> dict[str, Any]:
    stats = product["stats"]
    return {
        "source": "CMA",
        "product": product["product_name"],
        "element": frontend_meta["element"],
        "time": frontend_meta["time"],
        "level": frontend_meta["level"],
        "range": frontend_meta["range"],
        "resolution": _format_resolution(product["resolution"]),
        "grid": frontend_meta["grid"],
        "valid_grid": frontend_meta["grid"],
        "validGrid": frontend_meta["grid"],
        "coverage": product["coverage"],
        "missing": frontend_meta["missing"],
        "unit": frontend_meta["unit"],
        "variable_count": len(product["variable_names"]),
        "step_count": len(product["times"]) or product["file_count"],
        "vars": frontend_meta["vars"],
        "variables": frontend_meta["vars"],
        "steps": frontend_meta["steps"],
        "status": "已解析",
        "quality": "基础元数据解析完成",
        "max": _format_number(stats.get("max")),
        "min": _format_number(stats.get("min")),
        "mean": _format_number(stats.get("mean")),
        "alert": "无",
        "updated_at": datetime.now(timezone.utc).isoformat(),
        "bars": _bars(stats),
        "bars_labels": [],
        "trend": product["trend"],
        "trend_times": [_iso_time(value) for value in product["times"][: len(product["trend"])]],
    }


def _schema_variables(product: dict[str, Any]) -> list[dict[str, Any]]:
    stats_by_name = product.get("variable_stats") or {}
    variables = []
    for item in product["variables"]:
        name = item.get("name", "")
        variables.append(
            {
                "name": name,
                "long_name": item.get("long_name") or name,
                "short_name": item.get("short_name"),
                "raw_name": None,
                "name_cn": None,
                "unit": _clean_unit(item.get("unit")) or None,
                "display_unit": None,
                "shape": item.get("shape", []),
                "dims": item.get("dims", []),
                "level": item.get("level"),
                "missing": item.get("missing"),
                "stats": _schema_stats(stats_by_name.get(name)),
                "category": None,
                "description": None,
                "wavelength": None,
                "float32": _grid_url(product["files"][0], name),
                "netcdf": None,
                "png": None,
            }
        )
    return variables


def _schema_stats(stats: dict[str, Any] | None) -> dict[str, Any]:
    return {
        "min": stats.get("min") if isinstance(stats, dict) else None,
        "max": stats.get("max") if isinstance(stats, dict) else None,
        "mean": stats.get("mean") if isinstance(stats, dict) else None,
        "std": stats.get("std") if isinstance(stats, dict) else None,
    }


def _file_detail(source_file: Path, meta_file: Path, file_format: str, file_count: int) -> dict[str, Any]:
    return {
        "name": source_file.name,
        "path": source_file.as_posix(),
        "format": file_format,
        "parsed_at": datetime.now(timezone.utc).isoformat(),
        "parse_status": "success",
        "file_count": file_count,
    }


def _time_detail(product: dict[str, Any]) -> dict[str, Any]:
    times = [_iso_time(value) for value in product["times"]]
    step_hours = product.get("time_resolution_hours")
    return {
        "start": times[0] if times else None,
        "end": times[-1] if times else None,
        "count": len(times) or product["file_count"],
        "step_seconds": int(step_hours * 3600) if step_hours else None,
        "reference_time": None,
    }


def _spatial_detail(product: dict[str, Any]) -> dict[str, Any]:
    west, south, east, north = product["extent"]
    grid_shape = product["grid_shape"]
    resolution = product["resolution"]
    return {
        "lon_min": west,
        "lon_max": east,
        "lat_min": south,
        "lat_max": north,
        "resolution_lon": resolution.get("lon"),
        "resolution_lat": resolution.get("lat"),
        "nx": int(grid_shape[1]),
        "ny": int(grid_shape[0]),
    }


def _build_frames(files: list[Path], extent: list[float]) -> list[dict[str, Any]]:
    frames = []
    for index, path in enumerate(files):
        time_value = _parse_time_from_name(path)
        frames.append(
            {
                "index": index,
                "file": path.name,
                "source_file": path.as_posix(),
                "time": _iso_time(time_value),
                "raw_time": time_value,
                "time_label": _format_time(time_value),
                "extent": extent,
            }
        )
    return frames


def _series_files(source_file: Path, pattern: str) -> list[Path]:
    files = sorted(
        path
        for path in source_file.parent.glob(pattern)
        if path.is_file() and path.suffix.lower() == source_file.suffix.lower()
    )
    return files or [source_file]


def _infer_scope(source_file: Path) -> dict[str, str]:
    parts = [part for part in source_file.parts if part]
    parent_name = source_file.parent.name
    name_parts = [parent_name, source_file.name]

    region = ""
    resolution_label = ""

    if "_" in parent_name:
        candidate_region, candidate_resolution = parent_name.rsplit("_", 1)
        if candidate_region and candidate_resolution:
            region = candidate_region
            resolution_label = candidate_resolution

    if not resolution_label:
        for value in name_parts:
            match = RESOLUTION_RE.search(value)
            if match:
                resolution_label = match.group("resolution").upper().replace("P", ".")
                break

    if not region:
        for part in reversed(parts):
            if part.lower() in {"backend_system", "weather_agent", "desktop"}:
                continue
            if ":" in part:
                continue
            if part in {source_file.name, "NC", "GRIB", "CMA", "data"}:
                continue
            if "CMA" in part.upper() or "CRA40" in part.upper():
                continue
            if resolution_label and resolution_label in part:
                continue
            region = part
            break

    if region == "unknown":
        region = ""
    coverage = " ".join(item for item in [region, resolution_label] if item) or "区域数据"
    return {
        "region": region or "unknown",
        "resolution_label": resolution_label or "unknown",
        "coverage": coverage,
    }


def _open_hdf(path: Path) -> h5py.File:
    return h5py.File(io.BytesIO(path.read_bytes()), "r")


def _decode_attr(value: Any) -> Any:
    if value is None:
        return ""
    if isinstance(value, bytes):
        return value.decode("utf-8", errors="replace")
    if isinstance(value, np.bytes_):
        return bytes(value).decode("utf-8", errors="replace")
    if isinstance(value, np.ndarray) and value.shape == ():
        return _decode_attr(value.item())
    if isinstance(value, np.ndarray) and value.size == 1:
        return _decode_attr(value.reshape(-1)[0])
    if isinstance(value, np.ndarray):
        return value.tolist()
    return value


def _first_number(value: Any) -> float | str:
    if value is None:
        return ""
    if isinstance(value, str) and value == "":
        return ""
    try:
        return float(np.array(value).reshape(-1)[0])
    except Exception:
        return str(value)


def _parse_time_from_name(path: Path) -> str:
    match = TIME_RE.search(path.name)
    return match.group(1) if match else ""


def _format_time(value: str) -> str:
    if len(value) != 10:
        return value
    return f"{value[:4]}-{value[4:6]}-{value[6:8]} {value[8:10]}:00"


def _iso_time(value: str) -> str:
    if len(value) != 10:
        return value
    return f"{value[:4]}-{value[4:6]}-{value[6:8]}T{value[8:10]}:00:00Z"


def _time_span(product: dict[str, Any]) -> str:
    start = product.get("time_start") or ""
    end = product.get("time_end") or ""
    if start and end and start != end:
        return f"{start} - {end}"
    return start or end or "待解析"


def _time_resolution_hours(times: list[str]) -> int | None:
    if len(times) < 2:
        return None
    first = datetime.strptime(times[0], "%Y%m%d%H")
    second = datetime.strptime(times[1], "%Y%m%d%H")
    return int((second - first).total_seconds() / 3600)


def _format_range(extent: list[float]) -> str:
    west, south, east, north = extent
    return f"{west:.4f}E-{east:.4f}E, {south:.4f}N-{north:.4f}N"


def _resolution(west: float, east: float, width: int, south: float, north: float, height: int) -> dict[str, float | None]:
    lon_res = abs(east - west) / (width - 1) if width > 1 else None
    lat_res = abs(north - south) / (height - 1) if height > 1 else None
    return {
        "lon": round(lon_res, 6) if lon_res else None,
        "lat": round(lat_res, 6) if lat_res else None,
    }


def _format_resolution(resolution: dict[str, float | None]) -> str:
    lon = resolution.get("lon")
    lat = resolution.get("lat")
    if lon and lat:
        return f"{lon}° x {lat}°"
    return "待解析"


def _clean_unit(value: Any) -> str:
    text = str(value or "").strip()
    if len(text) >= 2 and text.startswith("[") and text.endswith("]"):
        return text[1:-1].strip()
    return text


def _grid_url(file_name: str, variable: str) -> str:
    from urllib.parse import urlencode

    return f"/api/cma/grid?{urlencode({'file': file_name, 'variable': variable, 'level_index': 0})}"


def _nc_dims(shape: tuple[int, ...], grid_shape: list[int]) -> list[str]:
    if list(shape) == grid_shape:
        return ["lat", "lon"]
    if len(shape) == 3 and list(shape[-2:]) == grid_shape:
        return ["profile", "lat", "lon"]
    return []


def _profile_level_name(size: int) -> str:
    return f"{size} soil profile layers"


def _pick_variable(names: list[str], preferred: tuple[str, ...]) -> str:
    for name in preferred:
        if name in names:
            return name
    return names[0] if names else "unknown"


def _variable_field(variables: list[dict[str, Any]], name: str, field: str) -> Any:
    for item in variables:
        if item["name"] == name:
            return item.get(field, "")
    return ""


def _clean_data(array: np.ndarray, missing: Any = None) -> np.ndarray:
    data = np.array(array, dtype="float64")
    missing_value = _first_number(missing)
    if isinstance(missing_value, float):
        data[data == missing_value] = np.nan
    data[np.isinf(data)] = np.nan
    return data


def _stats(values: list[np.ndarray]) -> dict[str, float | None]:
    finite_values = [item[np.isfinite(item)].reshape(-1) for item in values if np.isfinite(item).any()]
    if not finite_values:
        return {"min": None, "max": None, "mean": None}
    finite = np.concatenate(finite_values)
    if finite.size == 0:
        return {"min": None, "max": None, "mean": None}
    return {
        "min": round(float(np.nanmin(finite)), 6),
        "max": round(float(np.nanmax(finite)), 6),
        "mean": round(float(np.nanmean(finite)), 6),
    }


def _nc_stats(files: list[Path], variable: str) -> dict[str, float | None]:
    values: list[np.ndarray] = []
    for path in files:
        with _open_hdf(path) as dataset:
            if variable not in dataset or len(dataset[variable].shape) != 2:
                continue
            item = dataset[variable]
            values.append(_clean_data(item[:], item.attrs.get("_FillValue")))
    return _stats(values)


def _nc_trend(files: list[Path], variable: str) -> list[float]:
    trend: list[float] = []
    for path in files:
        with _open_hdf(path) as dataset:
            if variable not in dataset or len(dataset[variable].shape) != 2:
                continue
            item = dataset[variable]
            data = _clean_data(item[:], item.attrs.get("_FillValue"))
            trend.append(round(float(np.nanmean(data)), 6))
    return trend[:24]


def _grib_stats(files: list[Path], variable: str) -> dict[str, float | None]:
    values: list[np.ndarray] = []
    for path in files:
        with rasterio.open(path) as dataset:
            for band in range(1, dataset.count + 1):
                if dataset.tags(band).get("GRIB_ELEMENT") == variable:
                    values.append(_clean_data(dataset.read(band), dataset.nodata))
    return _stats(values)


def _grib_trend(files: list[Path], variable: str) -> list[float]:
    trend: list[float] = []
    for path in files:
        with rasterio.open(path) as dataset:
            for band in range(1, dataset.count + 1):
                if dataset.tags(band).get("GRIB_ELEMENT") == variable:
                    data = _clean_data(dataset.read(band), dataset.nodata)
                    trend.append(round(float(np.nanmean(data)), 6))
                    break
    return trend[:24]


def _format_number(value: Any) -> str:
    if value is None:
        return "待解析"
    try:
        return f"{float(value):.3f}"
    except Exception:
        return str(value)


def _bars(stats: dict[str, float | None]) -> list[float]:
    min_value = stats.get("min")
    max_value = stats.get("max")
    if min_value is None or max_value is None:
        return [0, 0, 0, 0, 0]
    return [round(float(value), 3) for value in np.linspace(float(min_value), float(max_value), 5)]
